apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  labels:
    app: argocd 
    entity: ci-cd 
spec:
  project: default
  source:
    repoURL: git@github.com:arjunavinfra/argocd.git
    targetRevision: HEAD
    path: Install
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true