apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    app: argocd 
    entity: ci
spec:
  project: default
  source:
    repoURL: git@github.com:arjunavinfra/argocd.git
    targetRevision: HEAD
    path: Install
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

    