apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  labels:
    app: sample 
    entity: test
spec:
  project: default
  source:
    repoURL: git@github.com:arjunavinfra/prometheus-operator.git
    targetRevision: HEAD
    path: argocd 
  destination:
    server: https://kubernetes.default.svc
    namespace: default

    