apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    chart: vault
    targetRevision: 0.15.0
    helm:
      parameters:
        # - name: server.ha.enabled
        #   value: 'true'
        # - name: server.ha.replicas
        #   value: '3'
        - name: ui.enabled
          value: 'true'
        - name: ui.serviceType
          value: LoadBalancer
        - name: ui.targetPort
          value: '8200'
        - name: ui.externalPort
          value: '8200'
      releaseName: vault
      values: |
        injector:
          enabled: false
        server:
          dev:
            enabled: true
          postStart:
            - /bin/sh
            - -c
            - |
              sleep 10s &&\
              printf 'path "secret/*"{\ncapabilities=["read"]\n}' | vault policy write argocd - &&\
              vault auth enable kubernetes &&\
              vault write auth/kubernetes/config\
                kubernetes_host=https://kubernetes.default.svc \
                disable_iss_validation=true &&\
              vault write auth/kubernetes/role/argocd \
                bound_service_account_names=argocd-repo-server \
                bound_service_account_namespaces=argocd \
                policies="argocd"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
