apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
spec:
  destination:
    name: ''
    namespace: vault
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://helm.releases.hashicorp.com'
    targetRevision: 0.23.0
    chart: vault
    helm:
      parameters:
        - name: server.ha.enabled
          value: 'true'
        - name: server.ha.replicas
          value: '3'
        - name: ui.serviceType
          value: LoadBalancer
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true