apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
spec:
  destination:
    name: ''
    namespace: hashicorp-vault
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://helm.releases.hashicorp.com'
    targetRevision: 0.23.0
    chart: vault
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: ui.serviceType
          value: LoadBalancer
        - name: server.dataStorage.size
          value: 5Gi
        - name: server.auditStorage.size
          value: 5Gi
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
