apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  labels:
    app: sample 
    entity: sample
spec:
  project: default
  source:
    repoURL: 'https://arjunavinfra.github.io/applications/app-helm/charts'
    targetRevision: 0.1.0
    helm:
      valueFiles:
        - values.yaml
    chart: helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true