apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: git@github.com:arjunavinfra/applications.git
      revision: HEAD
      directories:
      - path: podinfo/deploy/webapp/*
      # - path: charts
      #   exclude: true
      # - path: cmd
      #   exclude: true  
      # - path: cue
      #   exclude: true    
      # cmd 
      # cue 
      # deploy/bases
      # deploy/overlays 
      # deploy/secure 
      # deploy/webapp
      # kustomize 
      # otel
      # pkg 
      # test ui
  template:
    metadata:
      name: '{{.path.basename}}'
      labels:
        entity: app
        app: '{{.path.path}}'  
    spec:
      project: "default"
      source:
        repoURL: git@github.com:arjunavinfra/applications.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true