apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: obserability
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: git@github.com:arjunavinfra/prometheus-operator.git
      revision: HEAD
      directories:
      - path: manifests/*
      - path: manifests/blackboxexporter
        exclude: true
      - path: manifests/prometheusadapter
        exclude: true
      - path: manifests/minio
        exclude: true
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: git@github.com:arjunavinfra/prometheus-operator.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true